---
apiVersion: v1
kind: Namespace
metadata:
  name: malan-dev
spec:

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: malan
  name: malan
  namespace: malan-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: malan
  template:
    metadata:
      labels:
        app: malan
      namespace: malan-dev
    spec:
      containers:
      - image: docker.io/freedomben/malan-dev:latest
        name: malan
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
          protocol: TCP
        env:
        - name: DB_INIT
          value: 'Yes'
        - name: BIND_ADDR
          value: '0.0.0.0'
        - name: DB_USERNAME
          value: 'postgres'
        - name: DB_PASSWORD
          value: 'postgres'
        - name: DB_HOSTNAME
          value: 'localhost'
      - image: docker.io/postgres:12.6-alpine
        name: postgres
        imagePullPolicy: Always
        ports:
        - containerPort: 5432
          protocol: TCP
        env:
        - name: POSTGRES_USER
          value: 'postgres'
        - name: POSTGRES_PASSWORD
          value: 'postgres'

#---
#apiVersion: v1
#kind: Service
#metadata:
#  labels:
#    app: malan
#  name: malan
#  namespace: malan-dev
#spec:
#  type: NodePort
#  selector:
#    app: malan
#  ports:
#  - name: 4000-tcp
#    port: 4000
#    protocol: TCP
#    targetPort: 4000
#    nodePort: 30188

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: malan
  name: malan
  namespace: malan-dev
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-size-slug: "lb-small" # or lb-medium|lb-large
spec:
  type: NodePort
  selector:
    app: malan
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 4000
      nodePort: 30003
