version: "3"
services:
  postgres:
    image: 'postgres:12.6-alpine'
    volumes:
      - 'pgdata:/var/lib/postgresql/data'      # Use a docker volume for the database files
     #- './pgdata:/var/lib/postgresql/data:Z'  # to keep the volume in your local dir
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'

  mail:
    image: 'schickling/mailcatcher'
    ports:
      - '1025:1025'  # For SMTP
      - '1080:1080'  # For the web interface

  malan:
    build: .
    ports:
      - "4000:4000"
    environment:
      DB_INIT: 'Yes'
      DB_USERNAME: 'postgres'
      DB_PASSWORD: 'postgres'
      DB_HOSTNAME: 'postgres'
      BIND_ADDR: '0.0.0.0'
      SMTP_ENDPOINT: 'localhost'
      SMTP_PORT: '1025'
      SMTP_USERNAME: ''
      SMTP_PASSWORD: ''
    depends_on:
      - 'postgres'
      - 'mail'

volumes:
  pgdata:

