version: "3"
services:
  postgres:
    image: 'postgres:12.6-alpine'
    volumes:
      - 'pgdata:/var/lib/postgresql/data'      # Use a docker volume for the database files
     #- './pgdata:/var/lib/postgresql/data:Z'  # to keep the volume in your local dir
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'

  malan:
    build: .
    ports:
      - "4000:4000"
    environment:
      HOST: 'localhost'
      PORT: '4000'
      BIND_ADDR: '0.0.0.0'
      MAILGUN_DISABLE: 'Yes'
      DB_INIT: 'Yes'
      DB_USERNAME: 'postgres'
      DB_PASSWORD: 'postgres'
      DB_HOSTNAME: 'postgres'
      LOG_LEVEL: 'debug'
    depends_on:
      - 'postgres'

volumes:
  pgdata:

