---
apiVersion: v1
kind: Namespace
metadata:
  name: malan
spec:

---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: malan
  name: malan-migration-config
  namespace: malan
data:
  BIND_ADDR: '127.0.0.1'

---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: malan-migration
  name: malan-migration
  namespace: malan
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: malan-migration
        image: docker.io/freedomben/malan-prod:latest
        command: ["mix", "ecto.create.migrate"]
        envFrom:
          - configMapRef:
              name: malan-migration-config
          - secretRef:
              name: malan-secrets
  ttlSecondsAfterFinished: 86400 # 24 hours
  parallelism: 1
  completions: 1
  backoffLimit: 2
