---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: malan
  name: malan-secrets
  namespace: malan
type: Opaque
stringData:
  DB_USERNAME: 'doadmin'
  DB_PASSWORD: 'bl99r01m8z72m9hw'
  DB_HOSTNAME: 'db-postgresql-nyc3-45115-do-user-7165198-0.b.db.ondigitalocean.com'
  #DATABASE_URL: "ecto://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOSTNAME}/${DB_DATABASE}"
  DATABASE_URL: "ecto://doadmin:bl99r01m8z72m9hw@db-postgresql-nyc3-45115-do-user-7165198-0.b.db.ondigitalocean.com/malan-prod"
  SECRET_KEY_BASE: 'oKnimEajystJhqRd+nONXvyyp1liX/B+Jwimf/0V1HPH6yZEKe/4qYfMvyp/KK2f'

    #PGPASSWORD= pg_restore -U  -h  -p 25060 -d defaultdb
