---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: malan
  name: malan-migration-config
  namespace: malan-staging
data:
  BIND_ADDR: '127.0.0.1'
  DB_POOL_SIZE: '5'

---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: malan-migration
  name: malan-migration
  namespace: malan-staging
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: malan-migration
        image: docker.io/freedomben/malan-staging:2021-08-17a
        command: ["mix", "ecto.create.migrate"]
          #command: ["sleep", "36000"]
        envFrom:
          - configMapRef:
              name: malan-migration-config
          - secretRef:
              name: malan-secrets
  ttlSecondsAfterFinished: 86400 # 24 hours
  parallelism: 1
  completions: 1
  backoffLimit: 2
