import Config

# Configure your database
config :malan, Malan.Repo,
  username: System.get_env("DB_USERNAME") || "postgres",
  password: System.get_env("DB_PASSWORD") || "postgres",
  hostname: System.get_env("DB_HOSTNAME") || "127.0.0.1",
  port: System.get_env("DB_PORT") || "5432",
  database: "malan_dev",
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with esbuild to bundle .js and .css sources.
config :malan, MalanWeb.Endpoint,
  # If you want to use the digest version of the assets in dev, uncomment below
  # cache_static_manifest: "priv/static/cache_manifest.json",
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {0, 0, 0, 0}, port: 4000],
  # http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  # debug_errors: false,
  secret_key_base: "udX5bFf0B1XDP3LQdGk/neU0RDWp7LUf/ocaUT9lzJ80056EUKKuS7VKm71YYFhy",
  session_secure?: false,
  session_same_site: "Lax",
  watchers: [
    # Start the esbuild watcher by calling Esbuild.install_and_run(:default, args)
    esbuild: {Esbuild, :install_and_run, [:default, ~w(--sourcemap=inline --watch)]},
    npx: [
      "tailwindcss",
      "--input=css/app.css",
      "--output=../priv/static/assets/app.css",
      "--watch",
      cd: Path.expand("../assets", __DIR__)
    ]
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :malan, MalanWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$"E,
      ~r"priv/gettext/.*(po)$"E,
      ~r"lib/malan_web/(controllers|live|components|router)/.*(ex|heex)$"E,
      ~r"lib/malan_web/(views|templates)/.*(ex|eex|heex)$"E
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Configure swoosh mailer to use the local in memory mailbox
# config :malan, Malan.Mailer, adapter: Swoosh.Adapters.Local

# Configure swoosh mailer to use the logger mailbox which just prints
# out to the logs when mail is sent
config :malan, Malan.Mailer, adapter: Swoosh.Adapters.Logger

config :malan, :sentry, enabled: false
