import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :malan, MalanWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  # `force_ssl` is read by Phoenix.Endpoint via Application.compile_env, so it
  # must live in compile-time config (here) rather than config/runtime.exs —
  # otherwise Config.Provider aborts boot with a compile/runtime mismatch.
  # The values are static (no env-var inputs), so baking them in is safe.
  #
  # `log: false` silences Plug.SSL's per-request "redirecting GET /path to
  # https://..." info line. Every legitimate API caller, kubelet probe, and
  # external scraper that arrives over HTTP triggers one of these — including
  # a misconfigured Prometheus scraper that hits :4000/metrics on a 60s loop
  # (the real metrics endpoint is PromEx on :9568). The redirect itself and
  # HSTS still apply; we just stop logging an identical-shape line per hit.
  force_ssl: [hsts: true, rewrite_on: [:x_forwarded_proto], log: false],
  check_origin: [
    "https://malan.ameelio.org",
    "https://malan-prod.ameelio.org",
    "https://accounts.ameelio.org"
  ]

config :malan, :sentry, enabled: true
