import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :malan, MalanWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  check_origin: [
    "https://malan.ameelio.org",
    "https://malan-prod.ameelio.org",
    "https://accounts.ameelio.org"
  ]

# Do not print debug messages in production
config :logger, level: :info

config :malan, :sentry, enabled: true
